import { PresetSong } from '../types';

export function getInstrumentSuggestionsForGenre(genre?: string): string[] {
  const g = (genre || '').toLowerCase();

  if (g.includes('hip hop') || g.includes('rap') || g.includes('trap')) {
    return [
      '+vocals',
      '+808 sub-bass',
      '+trap drum beat',
      '+sample',
      '+synth melody',
      '+hi-hat rolls',
      '+backing ad-libs',
      '+snare / clap',
    ];
  }

  if (g.includes('rock') || g.includes('metal') || g.includes('punk') || g.includes('grunge')) {
    return [
      '+vocals',
      '+distorted electric guitar',
      '+bass guitar',
      '+acoustic drums',
      '+clean rhythm guitar',
      '+backing vocals',
      '+crash cymbals',
      '+guitar solo',
    ];
  }

  if (g.includes('edm') || g.includes('dance') || g.includes('house') || g.includes('techno') || g.includes('synth')) {
    return [
      '+vocals',
      '+synth lead',
      '+four-on-the-floor kick',
      '+sub-bass',
      '+sidechained pad',
      '+vocal chops',
      '+synth arpeggio',
      '+snare build-up',
    ];
  }

  if (g.includes('r&b') || g.includes('soul') || g.includes('neo-soul') || g.includes('funk')) {
    return [
      '+vocals',
      '+electric piano / rhodes',
      '+grooving bassline',
      '+smooth drums',
      '+horns / brass',
      '+backing harmonies',
      '+rhythm guitar',
      '+organ',
    ];
  }

  if (g.includes('pop')) {
    return [
      '+vocals',
      '+drums / beat',
      '+synth bass',
      '+electric guitar',
      '+acoustic piano',
      '+backing harmonies',
      '+string pad',
      '+synth lead',
    ];
  }

  if (g.includes('country') || g.includes('folk') || g.includes('acoustic')) {
    return [
      '+vocals',
      '+acoustic guitar',
      '+pedal steel guitar',
      '+upright / electric bass',
      '+acoustic drums',
      '+fiddle',
      '+banjo',
      '+harmonica',
    ];
  }

  // Generic popular music instruments fallback (starts with +vocals as required)
  return [
    '+vocals',
    '+drums / beat',
    '+bass guitar',
    '+electric piano / keys',
    '+electric guitar',
    '+synth pad',
    '+acoustic guitar',
    '+backing vocals',
  ];
}

export const PRESET_SONGS: PresetSong[] = [
  {
    name: 'Put Your Records On',
    title: 'Put Your Records On',
    artist: 'Corinne Bailey Rae',
    album: 'Corinne Bailey Rae',
    year: '2006',
    genre: 'Soul / R&B / Pop',
    referenceBpm: 96,
    timeSignature: '4/4',
    youtubeId: 'rjQ3WWxf9bE',
    youtubeUrl: 'https://www.youtube.com/watch?v=rjQ3WWxf9bE',
    description: 'Soulful 96 BPM acoustic soul hit with classic verse-chorus-bridge structure.',
    prepopulatedSections: [
      {
        id: 'sec-intro',
        type: 'intro',
        label: 'Intro',
        startTime: 0,
        endTime: 14,
        calculatedBars: 4,
        energyLevel: 4,
        rhythmicDrive: 5,
        vocalComplexity: 1,
        hasVocals: false,
        textureDensity: 3,
        instrumentationNotes: 'Warm electric guitar riff, light hi-hats, subtle finger snaps.',
      },
      {
        id: 'sec-v1',
        type: 'verse',
        label: 'Verse 1',
        startTime: 14,
        endTime: 42,
        calculatedBars: 8,
        energyLevel: 5,
        rhythmicDrive: 6,
        vocalComplexity: 6,
        hasVocals: true,
        textureDensity: 4,
        instrumentationNotes: 'Lead vocal enters with conversational phrasing, acoustic guitar strumming, bassline enters.',
      },
      {
        id: 'sec-pre1',
        type: 'verse',
        label: 'Verse 1.5',
        startTime: 42,
        endTime: 56,
        calculatedBars: 4,
        energyLevel: 6,
        rhythmicDrive: 7,
        vocalComplexity: 7,
        hasVocals: true,
        textureDensity: 5,
        instrumentationNotes: 'Vocals rise in pitch ("Girl, put your records on..."), drums intensify, organ pad fills the background.',
      },
      {
        id: 'sec-c1',
        type: 'chorus',
        label: 'Chorus/Hook 1',
        startTime: 56,
        endTime: 84,
        calculatedBars: 8,
        energyLevel: 8,
        rhythmicDrive: 8,
        vocalComplexity: 8,
        hasVocals: true,
        textureDensity: 7,
        instrumentationNotes: 'Full band in: rich backing harmonies, full drum kit groove, walking bass, hook lyrics repeat.',
      },
      {
        id: 'sec-v2',
        type: 'verse',
        label: 'Verse 2',
        startTime: 84,
        endTime: 112,
        calculatedBars: 8,
        energyLevel: 5,
        rhythmicDrive: 6,
        vocalComplexity: 6,
        hasVocals: true,
        textureDensity: 5,
        instrumentationNotes: 'Energy pulls back slightly; new lyrical story, subtle organ flourishes added compared to Verse 1.',
      },
      {
        id: 'sec-pre2',
        type: 'verse',
        label: 'Verse 2.5',
        startTime: 112,
        endTime: 126,
        calculatedBars: 4,
        energyLevel: 7,
        rhythmicDrive: 7,
        vocalComplexity: 7,
        hasVocals: true,
        textureDensity: 6,
        instrumentationNotes: 'Vocals ascend again with extra vocal ad-libs building momentum towards the second chorus.',
      },
      {
        id: 'sec-c2',
        type: 'chorus',
        label: 'Chorus/Hook 2',
        startTime: 126,
        endTime: 154,
        calculatedBars: 8,
        energyLevel: 8,
        rhythmicDrive: 8,
        vocalComplexity: 8,
        hasVocals: true,
        textureDensity: 8,
        instrumentationNotes: 'Full hook repetition with thicker backing vocals and tambourine added for heightened energy.',
      },
      {
        id: 'sec-bridge',
        type: 'bridge',
        label: 'Bridge',
        startTime: 154,
        endTime: 182,
        calculatedBars: 8,
        energyLevel: 7,
        rhythmicDrive: 6,
        vocalComplexity: 8,
        hasVocals: true,
        textureDensity: 6,
        instrumentationNotes: 'Chord progression changes, vocal melodies explore higher register ("The more things seem to change..."), reflective tone.',
      },
      {
        id: 'sec-c3',
        type: 'chorus',
        label: 'Chorus/Hook 3',
        startTime: 182,
        endTime: 210,
        calculatedBars: 8,
        energyLevel: 9,
        rhythmicDrive: 9,
        vocalComplexity: 9,
        hasVocals: true,
        textureDensity: 8,
        instrumentationNotes: 'Climax of the song! Gospel-style vocal runs, maximum texture, clapping.',
      },
      {
        id: 'sec-outro',
        type: 'outro',
        label: 'Outro',
        startTime: 210,
        endTime: 238,
        calculatedBars: 8,
        energyLevel: 5,
        rhythmicDrive: 5,
        vocalComplexity: 5,
        hasVocals: true,
        textureDensity: 4,
        instrumentationNotes: 'Groove continues as vocals vamp on "records on...", instruments gradually fade out to solo guitar finish.',
      },
    ],
  },
  {
    name: 'Musicology',
    title: 'Musicology',
    artist: 'Prince',
    album: 'Musicology',
    year: '2004',
    genre: 'Funk / R&B / Soul',
    referenceBpm: 116,
    timeSignature: '4/4',
    youtubeId: 'qdmWbJ8ISP4',
    youtubeUrl: 'https://www.youtube.com/watch?v=qdmWbJ8ISP4',
    description: 'The featured example song in the tutorial assignment. Grooving 116 BPM 4/4 funk/R&B masterpiece with classic structure.',
    prepopulatedSections: [
      {
        id: 'musicology-intro',
        type: 'intro',
        label: 'Intro',
        startTime: 0,
        endTime: 12,
        calculatedBars: 4,
        energyLevel: 5,
        rhythmicDrive: 7,
        vocalComplexity: 2,
        hasVocals: true,
        textureDensity: 4,
        instrumentationNotes: 'Funky rhythm guitar riff, tight drum beat, spoken intro count-in.',
      },
      {
        id: 'musicology-v1',
        type: 'verse',
        label: 'Verse 1',
        startTime: 12,
        endTime: 44,
        calculatedBars: 12,
        energyLevel: 7,
        rhythmicDrive: 8,
        vocalComplexity: 7,
        hasVocals: true,
        textureDensity: 6,
        instrumentationNotes: 'Driving funk bassline, syncopated rhythm guitars, Prince soulful lead vocals.',
      },
      {
        id: 'musicology-c1',
        type: 'chorus',
        label: 'Chorus / Hook',
        startTime: 44,
        endTime: 76,
        calculatedBars: 12,
        energyLevel: 9,
        rhythmicDrive: 9,
        vocalComplexity: 8,
        hasVocals: true,
        textureDensity: 8,
        instrumentationNotes: 'Explosive horn section joins, full backing harmonies ("Let\'s go back, back to the time...").',
      },
      {
        id: 'musicology-v2',
        type: 'verse',
        label: 'Verse 2',
        startTime: 76,
        endTime: 108,
        calculatedBars: 12,
        energyLevel: 7,
        rhythmicDrive: 8,
        vocalComplexity: 7,
        hasVocals: true,
        textureDensity: 6,
        instrumentationNotes: 'Name-dropping classic artists, continuing the signature funky groove.',
      },
      {
        id: 'musicology-c2',
        type: 'chorus',
        label: 'Chorus 2',
        startTime: 108,
        endTime: 140,
        calculatedBars: 12,
        energyLevel: 9,
        rhythmicDrive: 9,
        vocalComplexity: 8,
        hasVocals: true,
        textureDensity: 8,
        instrumentationNotes: 'Full chorus repeat with vibrant horn accents and syncopated rhythm.',
      },
      {
        id: 'musicology-bridge',
        type: 'bridge',
        label: 'Guitar Solo / Interlude',
        startTime: 140,
        endTime: 180,
        calculatedBars: 14,
        energyLevel: 10,
        rhythmicDrive: 9,
        vocalComplexity: 6,
        hasVocals: false,
        textureDensity: 9,
        instrumentationNotes: 'Virtuoso Prince electric guitar solo showcasing incredible funk technique.',
      },
      {
        id: 'musicology-outro',
        type: 'outro',
        label: 'Outro',
        startTime: 180,
        endTime: 238,
        calculatedBars: 18,
        energyLevel: 8,
        rhythmicDrive: 8,
        vocalComplexity: 7,
        hasVocals: true,
        textureDensity: 7,
        instrumentationNotes: 'Vamping on groove, call-and-response with the band, fading out.',
      },
    ],
  },
  {
    name: 'Hey Ya!',
    title: 'Hey Ya!',
    artist: 'OutKast',
    album: 'Speakerboxxx / The Love Below',
    year: '2003',
    genre: 'Hip Hop / Funk / Pop',
    referenceBpm: 160,
    timeSignature: '4/4',
    youtubeId: 'PWgvGjAhvIw',
    youtubeUrl: 'https://www.youtube.com/watch?v=PWgvGjAhvIw',
    description: 'Famous 160 BPM upbeat hit with the classic 2/4 metric hiccup bar in the phrase structure.',
    prepopulatedSections: [
      {
        id: 'heyya-intro',
        type: 'intro',
        label: 'Intro',
        startTime: 0,
        endTime: 12,
        calculatedBars: 8,
        energyLevel: 6,
        rhythmicDrive: 7,
        vocalComplexity: 3,
        hasVocals: true,
        textureDensity: 4,
        instrumentationNotes: 'Acoustic guitar strumming intro, spoken crowd banter ("One, two, three, uh!").',
      },
      {
        id: 'heyya-v1',
        type: 'verse',
        label: 'Verse 1',
        startTime: 12,
        endTime: 40,
        calculatedBars: 16,
        energyLevel: 7,
        rhythmicDrive: 8,
        vocalComplexity: 7,
        hasVocals: true,
        textureDensity: 6,
        instrumentationNotes: 'Driving acoustic guitar riff, energetic lead vocals ("My baby don\'t mess around...").',
      },
      {
        id: 'heyya-c1',
        type: 'chorus',
        label: 'Chorus / Hook',
        startTime: 40,
        endTime: 72,
        calculatedBars: 16,
        energyLevel: 9,
        rhythmicDrive: 9,
        vocalComplexity: 8,
        hasVocals: true,
        textureDensity: 8,
        instrumentationNotes: 'Explosive hook ("Hey ya! Oh, oh..."), full synth bass, handclaps, backing harmonies.',
      },
      {
        id: 'heyya-v2',
        type: 'verse',
        label: 'Verse 2',
        startTime: 72,
        endTime: 100,
        calculatedBars: 16,
        energyLevel: 7,
        rhythmicDrive: 8,
        vocalComplexity: 7,
        hasVocals: true,
        textureDensity: 6,
        instrumentationNotes: 'Second verse storytelling ("Now what\'s cooler than being cool? Ice cold!").',
      },
      {
        id: 'heyya-c2',
        type: 'chorus',
        label: 'Chorus / Hook 2',
        startTime: 100,
        endTime: 132,
        calculatedBars: 16,
        energyLevel: 9,
        rhythmicDrive: 9,
        vocalComplexity: 8,
        hasVocals: true,
        textureDensity: 8,
        instrumentationNotes: 'Repeated high-energy chorus hook with enthusiastic crowd call and response.',
      },
      {
        id: 'heyya-bridge',
        type: 'bridge',
        label: 'Bridge / Chant',
        startTime: 132,
        endTime: 168,
        calculatedBars: 18,
        energyLevel: 8,
        rhythmicDrive: 8,
        vocalComplexity: 9,
        hasVocals: true,
        textureDensity: 7,
        instrumentationNotes: '"Shake it, shake, shake it like a Polaroid picture!" chant builds tension.',
      },
      {
        id: 'heyya-outro',
        type: 'outro',
        label: 'Outro',
        startTime: 168,
        endTime: 215,
        calculatedBars: 12,
        energyLevel: 6,
        rhythmicDrive: 6,
        vocalComplexity: 5,
        hasVocals: true,
        textureDensity: 4,
        instrumentationNotes: 'Acoustic guitar fades out with spoken sign-off and final chord ring.',
      },
    ],
  },
  {
    name: 'Blinding Lights',
    title: 'Blinding Lights',
    artist: 'The Weeknd',
    album: 'After Hours',
    year: '2019',
    genre: 'Synthpop / 80s Pop',
    referenceBpm: 171,
    timeSignature: '4/4',
    youtubeId: '4NRXx6U8ABQ',
    youtubeUrl: 'https://www.youtube.com/watch?v=4NRXx6U8ABQ',
    description: '171 BPM driving synthwave pop with iconic 80s gated drums and soaring synth hooks.',
  },
  {
    name: 'Flowers',
    title: 'Flowers',
    artist: 'Miley Cyrus',
    album: 'Endless Summer Vacation',
    year: '2023',
    genre: 'Pop / Disco-Funk',
    referenceBpm: 118,
    timeSignature: '4/4',
    youtubeId: 'G7KNmW9a75Y',
    youtubeUrl: 'https://www.youtube.com/watch?v=G7KNmW9a75Y',
    description: '118 BPM disco-pop groove with infectious bassline and strong empowering hook.',
  },
];
